### ISSUE TITLE
not working on bionic and openstack stein

### ISSUE THREAD

**Issue by radumalica** [lfdominguez/cinder-freenas-charm#1]
Trying to deploy this juju charm with latest juju 2.6.9 and it fails with the following error inside the container

python-cinder-freenas: Depends: python-cinder but it is not going to be installed

it seems that this charm is made for python 2.x  and ubuntu bionic uses python3

apt install python-cinder

Depends: cinder-common (=2.13.0.0-0ubuntu3-cloud0) but 2:14.0.0-0ubuntu1-cloud0 is installed

apt list | grep cinder

python3-cinder/bionic-updates [installed]

**Comment by lfdominguez** [comment]
Sorry for the error, i will go to archive this project because i'm using ceph now.
